---
title: "Crops and Livestock Analysis"
author: "DCA Rgroup Project"
format: 
  html:
    theme: cosmo
    toc: true
    toc-title: "Contents"
    toc-depth: 2
---

## 1. Introduction

This project will analyze the production trends for crops and livestock products in Africa, using data from the FAO covering 278 agricultural products. The analysis will explore how production quantities, harvested arrears and yields have evolved across different crops and livestocks categories over the years. Additionally, it will investigate the relationship between yield and weather condition, pesticides.

### 1.1 Project Title

Crops and Livestock Production Analysis

### 1.2 Aim and Objectives

**Aim**: To develop a predictive model that accurately identifies customers who are likely to churn.

**Objectives**:

-   Explore the production trends for various crops and livestock categories (e.g rice, cassava, cattle, poultry etc).

-   Examine how area harvested, production quantity, and yield of crops and livestock have changed overtime in Africa.

-   Explore the relationship between yields and weather conditions, land are and pesticides use.

-   Identify key drivers that influence crop yields.

-   Create a dashboard to present insights and provide a brief summary of the findings

## 2. Data Information

### 2.1 Data Source

-   **Source**: This data is gotten from the Food and Agriculture Organization of the United Nations covering 278 agricultural products

-   **ription**: The dataset contains 278 agricultural product information.

### 2.2 Metadata

-   **Columns**:
    -   `customerID`: Unique identifier for each customer.
    -   `gender`: Gender of the customer.
    -   `SeniorCitizen`: Indicates if the customer is a senior citizen.
    -   `Partner`: Indicates if the customer has a partner.
    -   `Dependents`: Indicates if the customer has dependents.
    -   `tenure`: Number of months the customer has been with the company.
    -   `PhoneService`: Indicates if the customer has phone service.
    -   `MultipleLines`: Indicates if the customer has multiple lines.
    -   `InternetService`: Type of internet service the customer has.
    -   `OnlineSecurity`: Indicates if the customer has online security.
    -   `OnlineBackup`: Indicates if the customer has online backup.
    -   `DeviceProtection`: Indicates if the customer has device protection.
    -   `TechSupport`: Indicates if the customer has tech support.
    -   `StreamingTV`: Indicates if the customer has streaming TV.
    -   `StreamingMovies`: Indicates if the customer has streaming movies.
    -   `Contract`: Type of contract the customer has.
    -   `PaperlessBilling`: Indicates if the customer has paperless billing.
    -   `PaymentMethod`: Method of payment used by the customer.
    -   `MonthlyCharges`: Monthly charges incurred by the customer.
    -   `TotalCharges`: Total charges incurred by the customer.
    -   `Churn`: Indicates if the customer has churned.

## 3. Research Questions

-   What are the yield trends across Africa for major crops and livestocks ?

-   How do this trends differ between primary and processed crop and livestock product?

-   Which countries are the largest producers of key crops and livestock products?

-   Are there specific crops or livestock products that show a consistent upward or downward trends in yields?

-   How accurate can we predict yields from key drivers that influence crop yield?

## 4. Data Cleaning

-   Handle missing values.
-   Correct data types (e.g., convert `TotalCharges` to numeric).
-   Remove duplicates.

## 5. Data Preprocessing

-   Normalize numerical features.
-   Encode categorical features.
-   Split the data into training and testing sets.

## 6. Data Exploration

-   Summary statistics of the data.
-   Visualizations (e.g., histograms, bar charts, correlation matrix).
-   Insights from exploratory data analysis.

## 7. Modelling

-   Define and train multiple models (e.g., logistic regression, decision tree, random forest).
-   Evaluate models using metrics such as accuracy, precision, recall, ROC curve, feature importance and F1 score.
-   Select the best-performing model.
-   Summary of findings and recommendations

## 8. Dashboard Building

-   Use Quarto to create an interactive dashboard.
-   Include sections for model performance metrics, ROC curve, feature importance, and customer segmentation.
-   Add interactive filters and visualizations.

## 9. Deployment

-   Deploy the dashboard using a web hosting service (e.g., GitHub Pages, Netlify).
-   Ensure the dashboard is accessible and user-friendly.

## 10. Collaborators

-   **R4DataScienceNigeria Team**:
    -   Collaborator 1
    -   Collaborator 2
    -   Collaborator 3

## 11. Collaboration and Version Control

-   Initialize a git repository `git init`

-   Add files to the repo `git add`

-   Commit changes \`git commit -m "Initial commit"

-   Push to Github `git push`
